from speechmodel import textToAudio
from video import video_generator
from imagemodel import textToImage

ACCESS_ID = "AKIAJC5DJDYWVW3FTJBA"
ACCESS_KEY = "puIHOC5IICfQICGP/Gq78OM35SQBDpCwNJTdyvDg"
region_name = "us-east-2"
#sample_text = "Spider-Man is a fictional superhero appearing in American comic books published by Marvel Comics. The character was created by writer-editor Stan Lee and writer-artist Steve Ditko, and first appeared in the anthology comic book Amazing Fantasy #15 (August 1962) in the Silver Age of Comic Books. The character is conceived as an orphan within the Marvel Universe named Peter Parker being raised by his Aunt May and Uncle Ben in New York City after his parents Richard and Mary Parker were killed in a plane crash. Lee and Ditko depicted the character as having to deal with the normal struggles of adolescence and financial issues with a large array of supporting characters such as J. Jonah Jameson, Daily Bugle editor and smear campaigner of Spider-Man and classmates such as Flash Thompson, Harry Osborn and romantic interests, Gwen Stacy and Mary Jane Watson. His origin story depicts him as being bitten by a radioactive spider and thus acquiring spider-related power and abilities, such as the ability to cling to most surfaces, shoot spider-webs using wrist-mounted devices of his own invention, which he calls " + 'web-shooters' + ", and react to danger quickly with his " + 'spider-sense' + ", enabling him to combat his many superpowered foes, such as Doctor Octopus, Green Goblin and Venom. Also within the origin story, Spider-Man originally uses this power for stardom, but after letting a burglar escape who is responsible for shooting his uncle, he learns to use his power responsibly."

#sample_text += "When Spider-Man first appeared in the early 1960s, teenagers in superhero comic books were usually relegated to the role of sidekick to the protagonist. The Spider-Man series broke ground by featuring Peter Parker, the high school student from Queens behind Spider-Man's secret identity and with whose " + "self-obsessions with rejection, inadequacy, and loneliness" +  "young readers could relate.[9] While Spider-Man had all the makings of a sidekick, unlike previous teen heroes such as Bucky and Robin, Spider-Man had no superhero mentor like Captain America and Batman; he thus had to learn for himself that " + "with great power there must also come great responsibility" + "—a line included in a text box in the final panel of the first Spider-Man story but later retroactively attributed to his guardian, the late Uncle Ben."
#sample_text = 'Shiva is a Good boy. Sanjay is a Chutiya boy. Dakshit is not a boy.'
no_of_sentences = 3
folder_name = 'audio'
sample_text = "Dana Vespoli walks the campy tightrope in 'My Evil Stepson', a 4- vignette melodrama that combines her dramatic talents with the bottom-feeding antics associated with her Evil Angel releases.This is immediately apparent in the opening segment, in which Dana's go- to actress Sovereign Syre is giving a sincere performance as a lady-in- jeopardy, when suddenly her stepson arrives in a hoodie (looking uncannily like Rami Malek in 'Mr. Robot') in the form of Xander Corvus who whispers his dialog as he rapes his step-mom. But this isn't rape, just crappy role-playing and is staged in a graffiti-laden tunnel for the cinema of ugliness content.Dana appears in a segment where she suffers similar abuse and humiliation but once again we are painfully aware of the 'and she loved it!' mentality that drags so much porn down to the low level of the dumbest or most venal customer. Cast against his usual smiling young heart-throb type, Tyler Nixon does the honors as Dana's evil step-son. Uncredited cameo as a drug dealer in this episode looked like Chad Diamond.Super-MILFs Cherie DeVille and the tattooed lady Nina Elle suffer similar fates, and Cherie's trademark ingratiating smile signals rather too obviously that this nonsense is all in good fun. I much prefer when Dana ventures into dark territory without sending up her material, but this 'evil' titled opus is unfortunately closer to Tod Slaughter than Eugene O'Neill. Perhaps Ms. Vespoli is angling to finally crossover into what we call the mainstream by being hired for an 'American Horror Story' season."
# Object for generating Audio
sample_text = "Set in 1303 AD medieval India, Padmaavat is the story of honor, valor and obsession. Queen Padmavati is known for her exceptional beauty along with a strong sense of justice and is the wife of Maharawal Ratan Singh and pride of the Kingdom of Chittor, a prosperous kingdom in the north west of India. The legend of her beauty reaches the reigning sultan of Hindustan – Allaudin Khilji. The sultan who is a tyrant, is fixated with wanting anything that is of exceptional beauty for himself. He lays siege on the impregnable fortress of Chittorgarh. After a grueling 6 months, he returns empty handed. He becomes obsessed and now wants to capture Chittor and its Queen at any cost. He returns with a bigger army and ranging fury. He attacks Chittor with brutal force and a bloody and fearsome battle takes places between the righteous Maharawal Ratan Singh defending his kingdom and the honor of his queen and Sultan Allaudin Khilji. Khilji manages to breach the fortress but in vain as the Queen chooses to make the ultimate sacrifice to protect her dignity."
TTA = textToAudio(ACCESS_ID = ACCESS_ID, ACCESS_KEY = ACCESS_KEY, region_name = region_name)
# Object for generating Images
TTI = textToImage()
# Returns paragraph list and saves audio in a folder named audio
para_list = TTA.generate_audio(text = sample_text, no_of_sentences = no_of_sentences, folder_name = folder_name) 
# Returns Tags paragraph wise and saves images to the photos folder
print(para_list)
tags = TTI.getTags(para_list = para_list, get_urls = False, download = True)
video_generator(para_list, tags)

