# Generated by Django 2.0 on 2018-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.TextField(max_length=20000),
        ),
    ]
